version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    container_name: 'postgres-db'
  redis:
    image: 'redis:latest'
    restart: always
    container_name: 'redis-db'
  api:
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - redis
      - postgres
  client:
    container_name: client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    container_name: worker
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    container_name: nginx
    restart: always
    build:
     dockerfile: Dockerfile.dev
     context: ./nginx
    ports:
      - '8080:80' 
    depends_on:
      - client
      - api
